spring:
  datasource:
    url: jdbc:mysql://localhost:3307/celmade_db?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: celmade_root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

server:
  port: 8081

logging:
  level:
    com.celmade: DEBUG
    org.springframework.security: DEBUG 